/* The season, as it actually is.
 *
 * Generated by `scripts/build-schedule.mjs` and committed, because `lock_ts`
 * goes on chain at pool creation and `submit_pick` enforces it to the second.
 * These are not estimates: they are part of the deal a member joins, and a file
 * that moved under a running season would move deadlines people had already
 * planned around.
 *
 * WHAT THIS REPLACES. Locks used to be WEEK_1_KICKOFF plus seven days a week.
 * That was wrong twice over. The anchor was a day late for 2026, which would
 * have kept picks open for a full day after the opener was played. And real
 * weeks are not seven days apart at all — week one to week two is eight, week
 * twelve moves for Thanksgiving, week eighteen opens on a Saturday afternoon —
 * so the arithmetic drifted three days out by the end of the season.
 */

import raw from "@/data/nfl-schedule-2026.json";
import { teamByAbbr, TEAMS } from "@/lib/nfl";

export type Game = {
  /** Team abbreviations, already normalized to the on-chain index's spelling. */
  away: string;
  home: string;
  /** Unix seconds. */
  kickoff: number;
};

export type SeasonWeek = {
  week: number;
  /** The week's FIRST kickoff. This is the lock, and the lock is the product. */
  lockTs: number;
  /** Teams not playing at all. Unpickable, per the spec. */
  byes: string[];
  games: Game[];
};

const SCHEDULE = raw as {
  season: number;
  generated: string;
  source: string;
  weeks: SeasonWeek[];
};

export const SEASON_YEAR = SCHEDULE.season;

/** A week, 1-indexed as the program counts them, or null if out of range. */
export function weekOf(week: number): SeasonWeek | null {
  return SCHEDULE.weeks.find((w) => w.week === week) ?? null;
}

/** Every lock in the season, in order. What `create_pool` is handed. */
export function realLockSchedule(): number[] {
  return SCHEDULE.weeks.map((w) => w.lockTs);
}

/** The week's games, in kickoff order. Empty if the week is unknown. */
export function gamesFor(week: number): Game[] {
  return weekOf(week)?.games ?? [];
}

/* Teams not playing, as a bitmask in the same shape as `used_mask`.
 *
 * A member who picks a team on a bye is not making a risky pick, they are
 * making an impossible one: the program has no notion of a team that did not
 * play, so an unmarked team is a loss and they are simply out. The spec says
 * twice that these must be unselectable, and this is the number that makes
 * that cheap to enforce. */
export function byeMask(week: number): number {
  const w = weekOf(week);
  if (!w) return 0;
  let mask = 0;
  for (const abbr of w.byes) {
    const team = teamByAbbr(abbr);
    if (team) mask = (mask | (1 << team.i)) >>> 0;
  }
  return mask;
}

/** Is this team idle this week? */
export function isOnBye(week: number, team: number): boolean {
  return team >= 0 && team < TEAMS.length && (byeMask(week) & (1 << team)) !== 0;
}
