/* GENERATED by scripts/build-midfield-logo.mjs from drawMidfieldLogo in
 * src/lib/pixel.ts. Do not edit; re-run the script when the drawing changes.
 *
 * The midfield logo the game paints, as a 35x35 transparent PNG,
 * so the landing page shows the same drawing rather than a lookalike. */

export const MIDFIELD_LOGO_SIZE = 35;

export const MIDFIELD_LOGO =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACMAAAAjCAYAAAAe2bNZAAAA0ElEQVR42s3YwQmAMAwF0O7mJM7hno4gXrwLIoqCoLZqm/zEL/TkoY82adKGAPimeayD97dNmhpLU7VP/8wQ26SlA4bSIKAoJEQFQiNSKApINshia8Rb5gX5XJ1SSD90yzHgIMmqnEFSXITRrIoWE4FyMUhAElOSQffJkZgdpM0g6FYhA9cdYxo3UszbeSNOcauYccPQxAwyg5IY5FZJzp9LBf87bkTlwKo+mRXL31oIRH8Da7BM+2CqHpjqdkB3b6K7UdLdteleISjfZ7xerlbSH0b/YI7kCgAAAABJRU5ErkJggg==";
