/* GENERATED by scripts/build-midfield-logo.mjs from drawMidfieldLogo in
 * src/lib/pixel.ts. Do not edit; re-run the script when the drawing changes.
 *
 * The midfield logo the game paints, as a 51x51 transparent PNG,
 * so the landing page shows the same drawing rather than a lookalike. */

export const MIDFIELD_LOGO_SIZE = 51;

export const MIDFIELD_LOGO =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADMAAAAzCAYAAAA6oTAqAAAA+klEQVR42u3aSwrDMAwEUN8tJ+k5es8cIXTTfaGUhCwKhX5CHM2MPHXAq2z8sOWfVArhuz9up9LSt3b4W5vPw/jrfzrA2uHaJoVFALZgTSOoKCYECmIjPqEsIGGgLJDDoGyQalBWyG6QYtWCrXIRkMt1mp9NNjpRI8LAbIJsMNFxIgXVYl47vbdBMEdGRY15A3VM1rixwURvktKp1jFZl2j0oZIaNx3jjrGLGSXID8O486PjhnKcaR6jmGq+GNT9n4EJvTar44b2qIEGUZ6aUmDQIMgm+TdvzVZZALv8jF3mzC6naZdttqsDsKvQsKudsaxqsqw3y1YJuACbCJuq72QcjwAAAABJRU5ErkJggg==";
